// Auto-generated by scripts/embed_chakra_glyphs.py — do not edit.
#pragma once

#include <stdint.h>

#define CHAKRA_GLYPH_SIZE 96
#define CHAKRA_GLYPH_COUNT 7

extern const uint8_t kChakraGlyphAlpha[CHAKRA_GLYPH_COUNT][CHAKRA_GLYPH_SIZE * CHAKRA_GLYPH_SIZE];
