#pragma once

#include <stdint.h>

#define FACULTY175_LENORMAND_GLYPH_COUNT 36
#define FACULTY175_LENORMAND_GLYPH_W 48
#define FACULTY175_LENORMAND_GLYPH_H 48
#define FACULTY175_LENORMAND_GLYPH_ROW_BYTES 192
#define FACULTY175_LENORMAND_GLYPH_BYTES 9216
#define FACULTY175_LENORMAND_GLYPH_PATH "/bust_cache/lenormand/noto_color_emoji_48_argb.bin"
