"""Emit pm_build_info.h with git branch, SHA, and GitHub QR URL for the Version face."""
Import("env")

import subprocess
from pathlib import Path

REPO = "CastaliaInstitute/astrolabe"
OUT = Path(env["PROJECT_DIR"]) / "sketches" / "PocketMynah" / "pm_build_info.h"


def _run_git(*args: str) -> str:
    try:
        return (
            subprocess.check_output(["git", *args], cwd=env["PROJECT_DIR"], stderr=subprocess.DEVNULL)
            .decode("utf-8", errors="replace")
            .strip()
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def _c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_build_info():
    sha_full = _run_git("rev-parse", "HEAD") or "unknown"
    sha_short = _run_git("rev-parse", "--short", "HEAD") or sha_full[:7]
    branch = _run_git("rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    dirty = _run_git("status", "--porcelain") != ""
    date = _run_git("show", "-s", "--format=%cs", "HEAD") or "unknown"

    if branch == "HEAD":
        branch = "detached"

    if sha_full != "unknown":
        qr_url = f"https://github.com/{REPO}/commit/{sha_full}"
    else:
        qr_url = f"https://github.com/{REPO}"

    lines = [
        "#pragma once",
        "/** Generated by extra_script_build_info.py — do not edit. */",
        f'#define PM_BUILD_GIT_SHA "{_c_escape(sha_short)}"',
        f'#define PM_BUILD_GIT_SHA_FULL "{_c_escape(sha_full)}"',
        f'#define PM_BUILD_BRANCH "{_c_escape(branch)}"',
        f"#define PM_BUILD_DIRTY {1 if dirty else 0}",
        f'#define PM_BUILD_DATE "{_c_escape(date)}"',
        f'#define PM_BUILD_QR_URL "{_c_escape(qr_url)}"',
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")


emit_build_info()
