// Auto-generated by scripts/gen_moon_tex.py — do not edit by hand.
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define kPmMoonTexSize 466
#define kPmMoonTexPixels (466 * 466)
extern const uint8_t kPmMoonTexGray[kPmMoonTexPixels];

#ifdef __cplusplus
}
#endif
