[platformio]
src_dir = main
default_envs = astrolabe-cspot-s3-185-v2

[env]
platform = espressif32@6.13.0
framework = espidf
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.psram = opi
monitor_speed = 115200
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
upload_speed = 921600
build_flags =
  -DBOARD_HAS_PSRAM
  -DASTROLABE_WAVESHARE_S3_185=1
  -DASTROLABE_CSPOT_DEVICE_NAME='"Astrolabe 1.85"'

[env:astrolabe-cspot-s3-185-v1]
build_flags =
  ${env.build_flags}
  -DASTROLABE_WAVESHARE_S3_185_V1=1

[env:astrolabe-cspot-s3-185-v2]
build_flags =
  ${env.build_flags}
  -DASTROLABE_WAVESHARE_S3_185_V2=1
