// Auto-generated by scripts/embed_planet_glyphs.py — do not edit.
#pragma once

#include <stdint.h>

#define PLANET_GLYPH_SIZE 22
#define PLANET_GLYPH_COUNT 7

extern const uint8_t kPlanetGlyphAlpha[PLANET_GLYPH_COUNT][PLANET_GLYPH_SIZE * PLANET_GLYPH_SIZE];
