// Auto-generated by scripts/embed_zodiac_glyphs.py — do not edit.
#pragma once

#include <stdint.h>

#define ZODIAC_GLYPH_SIZE 32
#define ZODIAC_GLYPH_COUNT 12

extern const uint8_t kZodiacGlyphAlpha[ZODIAC_GLYPH_COUNT][ZODIAC_GLYPH_SIZE * ZODIAC_GLYPH_SIZE];
