#pragma once

#ifndef CONFIG_UAC_SPEAKER_CHANNEL_NUM
#define CONFIG_UAC_SPEAKER_CHANNEL_NUM 2
#endif
#ifndef CONFIG_UAC_SAMPLE_RATE
#define CONFIG_UAC_SAMPLE_RATE 48000
#endif

#ifndef CFG_TUD_AUDIO
#define CFG_TUD_AUDIO 1

#ifndef CFG_TUD_AUDIO_ENABLE_EP_OUT
#define CFG_TUD_AUDIO_ENABLE_EP_OUT 1
#endif
#ifndef CFG_TUD_AUDIO_ENABLE_EP_IN
#define CFG_TUD_AUDIO_ENABLE_EP_IN 0
#endif
#ifndef CFG_TUD_AUDIO_ENABLE_FEEDBACK_EP
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_EP 1
#endif
#ifndef CFG_TUD_AUDIO_ENABLE_FEEDBACK_FORMAT_CORRECTION
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_FORMAT_CORRECTION 1
#endif

#ifndef CFG_TUD_AUDIO_FUNC_1_N_FORMATS
#define CFG_TUD_AUDIO_FUNC_1_N_FORMATS 1
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_N_AS_INT
#define CFG_TUD_AUDIO_FUNC_1_N_AS_INT 1
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ
#define CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ 64
#endif

#ifndef CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE
#define CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE CONFIG_UAC_SAMPLE_RATE
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX 0
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX CONFIG_UAC_SPEAKER_CHANNEL_NUM
#endif

#ifndef CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX 2
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX 16
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_FORMAT_1_FRAME_SZ_RX
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_FRAME_SZ_RX \
  (CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX * CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX)
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX 2
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX 16
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_FORMAT_1_FRAME_SZ_TX
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_FRAME_SZ_TX \
  (CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX * CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX)
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_FORMAT_1_EP_SZ_OUT
#define CFG_TUD_AUDIO_FUNC_1_FORMAT_1_EP_SZ_OUT \
  (((CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE / 1000) + 1) * CFG_TUD_AUDIO_FUNC_1_FORMAT_1_FRAME_SZ_TX)
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX CFG_TUD_AUDIO_FUNC_1_FORMAT_1_EP_SZ_OUT
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ (CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX * 8)
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX 0
#endif
#ifndef CFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ 0
#endif

#ifndef CFG_TUD_AUDIO_ENABLE_DECODING
#define CFG_TUD_AUDIO_ENABLE_DECODING 0
#endif
#ifndef CFG_TUD_AUDIO_ENABLE_ENCODING
#define CFG_TUD_AUDIO_ENABLE_ENCODING 0
#endif

#ifndef CFG_TUD_AUDIO_FUNC_1_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN \
  (8 + 9 + 9 + 8 + 17 + (6 + ((CONFIG_UAC_SPEAKER_CHANNEL_NUM + 1) * 4)) + 12 + 9 + 9 + 16 + 6 + 7 + 8 + 7)
#endif

#endif
