/*
 * UAC build-local TinyUSB configuration.
 *
 * Arduino-ESP32 2.x ships an esp32s3 Arduino TinyUSB include tree whose
 * tusb_config.h still hardcodes OPT_MCU_ESP32S2. The UAC env prepends this
 * sketch directory to CPPPATH so the audio class and app code agree on S3.
 */
#pragma once

#include "sdkconfig.h"
#include "tusb_option.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef CONFIG_TINYUSB_CDC_ENABLED
#define CONFIG_TINYUSB_CDC_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_MSC_ENABLED
#define CONFIG_TINYUSB_MSC_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_HID_ENABLED
#define CONFIG_TINYUSB_HID_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_MIDI_ENABLED
#define CONFIG_TINYUSB_MIDI_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_VIDEO_ENABLED
#define CONFIG_TINYUSB_VIDEO_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_CUSTOM_CLASS_ENABLED
#define CONFIG_TINYUSB_CUSTOM_CLASS_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_DFU_RT_ENABLED
#define CONFIG_TINYUSB_DFU_RT_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_DFU_ENABLED
#define CONFIG_TINYUSB_DFU_ENABLED 0
#endif
#ifndef CONFIG_TINYUSB_VENDOR_ENABLED
#define CONFIG_TINYUSB_VENDOR_ENABLED 0
#endif

#ifndef CONFIG_TINYUSB_CDC_RX_BUFSIZE
#define CONFIG_TINYUSB_CDC_RX_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_CDC_TX_BUFSIZE
#define CONFIG_TINYUSB_CDC_TX_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_MSC_BUFSIZE
#define CONFIG_TINYUSB_MSC_BUFSIZE 512
#endif
#ifndef CONFIG_TINYUSB_HID_BUFSIZE
#define CONFIG_TINYUSB_HID_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_MIDI_RX_BUFSIZE
#define CONFIG_TINYUSB_MIDI_RX_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_MIDI_TX_BUFSIZE
#define CONFIG_TINYUSB_MIDI_TX_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_VIDEO_STREAMING_IFS
#define CONFIG_TINYUSB_VIDEO_STREAMING_IFS 0
#endif
#ifndef CONFIG_TINYUSB_VIDEO_STREAMING_BUFSIZE
#define CONFIG_TINYUSB_VIDEO_STREAMING_BUFSIZE 0
#endif
#ifndef CONFIG_TINYUSB_DFU_BUFSIZE
#define CONFIG_TINYUSB_DFU_BUFSIZE 1024
#endif
#ifndef CONFIG_TINYUSB_VENDOR_RX_BUFSIZE
#define CONFIG_TINYUSB_VENDOR_RX_BUFSIZE 64
#endif
#ifndef CONFIG_TINYUSB_VENDOR_TX_BUFSIZE
#define CONFIG_TINYUSB_VENDOR_TX_BUFSIZE 64
#endif

#define CFG_TUSB_MCU OPT_MCU_ESP32S3
#define CFG_TUSB_RHPORT0_MODE OPT_MODE_DEVICE
#define CFG_TUSB_OS OPT_OS_FREERTOS

#ifndef CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_SECTION
#endif
#ifndef CFG_TUSB_MEM_ALIGN
#define CFG_TUSB_MEM_ALIGN TU_ATTR_ALIGNED(4)
#endif

#define CFG_TUD_MAINTASK_SIZE 4096
#define CFG_TUD_ENDOINT0_SIZE 64

#define CFG_TUD_CDC CONFIG_TINYUSB_CDC_ENABLED
#define CFG_TUD_MSC CONFIG_TINYUSB_MSC_ENABLED
#define CFG_TUD_HID CONFIG_TINYUSB_HID_ENABLED
#define CFG_TUD_MIDI CONFIG_TINYUSB_MIDI_ENABLED
#define CFG_TUD_VIDEO CONFIG_TINYUSB_VIDEO_ENABLED
#define CFG_TUD_CUSTOM_CLASS CONFIG_TINYUSB_CUSTOM_CLASS_ENABLED
#define CFG_TUD_DFU_RUNTIME CONFIG_TINYUSB_DFU_RT_ENABLED
#define CFG_TUD_DFU CONFIG_TINYUSB_DFU_ENABLED
#define CFG_TUD_VENDOR CONFIG_TINYUSB_VENDOR_ENABLED

#define CFG_TUD_CDC_RX_BUFSIZE CONFIG_TINYUSB_CDC_RX_BUFSIZE
#define CFG_TUD_CDC_TX_BUFSIZE CONFIG_TINYUSB_CDC_TX_BUFSIZE
#define CFG_TUD_MSC_BUFSIZE CONFIG_TINYUSB_MSC_BUFSIZE
#define CFG_TUD_HID_BUFSIZE CONFIG_TINYUSB_HID_BUFSIZE
#define CFG_TUD_MIDI_RX_BUFSIZE CONFIG_TINYUSB_MIDI_RX_BUFSIZE
#define CFG_TUD_MIDI_TX_BUFSIZE CONFIG_TINYUSB_MIDI_TX_BUFSIZE
#define CFG_TUD_VIDEO_STREAMING CONFIG_TINYUSB_VIDEO_STREAMING_IFS
#define CFG_TUD_VIDEO_STREAMING_EP_BUFSIZE CONFIG_TINYUSB_VIDEO_STREAMING_BUFSIZE
#define CFG_TUD_DFU_XFER_BUFSIZE CONFIG_TINYUSB_DFU_BUFSIZE
#define CFG_TUD_VENDOR_RX_BUFSIZE CONFIG_TINYUSB_VENDOR_RX_BUFSIZE
#define CFG_TUD_VENDOR_TX_BUFSIZE CONFIG_TINYUSB_VENDOR_TX_BUFSIZE

#include "pm_usb_uac_tinyusb_config.h"

#ifdef __cplusplus
}
#endif
