#!/usr/bin/env python3
"""Build firmware RGB565 Earth texture from NASA SVS Blue Marble."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SRC = ROOT / "assets" / "earth" / "nasa-blue-marble-320x160.jpg"
DEFAULT_OUT = ROOT / "faculty175" / "main" / "faculty175_face_scale_earth_texture.h"


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", type=Path, default=DEFAULT_SRC)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--width", type=int, default=96)
    ap.add_argument("--height", type=int, default=48)
    args = ap.parse_args()

    im = Image.open(args.src).convert("RGB")
    im = im.resize((args.width, args.height), Image.Resampling.LANCZOS)

    values: list[int] = []
    for r, g, b in im.getdata():
        values.append(rgb565(r, g, b))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/embed_earth_texture.py; do not edit.\n")
        f.write("// Source: NASA SVS Blue Marble, https://svs.gsfc.nasa.gov/2915/\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define FACULTY175_EARTH_TEX_W {args.width}\n")
        f.write(f"#define FACULTY175_EARTH_TEX_H {args.height}\n\n")
        f.write("static const uint16_t k_faculty175_earth_tex_rgb565[] = {\n")
        for y in range(args.height):
            row = values[y * args.width : (y + 1) * args.width]
            f.write("    ")
            f.write(", ".join(f"0x{v:04x}" for v in row))
            f.write(",\n")
        f.write("};\n")

    print(f"Wrote {args.out} ({args.width}x{args.height}, {len(values) * 2} bytes)")


if __name__ == "__main__":
    main()
