#!/usr/bin/env python3
"""Download chakra yantra PNGs from Wikimedia Commons and embed alpha masks.

Sources: CC BY-SA 3.0 yantra diagrams (Mirzolot2 et al. on Commons).
Run: pip install pillow requests && python3 scripts/embed_chakra_glyphs.py
"""
from __future__ import annotations

import argparse
import sys
import urllib.parse
import urllib.request
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("pip install pillow requests", file=sys.stderr)
    raise

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets" / "chakra"
OUT_DIR = ROOT / "sketches" / "Astrolabe" / "faces" / "chakra"

# Commons yantras (Mirzolot2 et al., CC BY-SA 3.0) via Special:FilePath.
CHAKRAS = (
    ("root", "Muladhara.svg"),
    ("sacral", "Swadhisthana.svg"),
    ("solar", "Manipura.svg"),
    ("heart", "Anahata green.svg"),
    ("throat", "Vishuddhi.svg"),
    ("third_eye", "Ajna.svg"),
    ("crown", "Sahasrara.svg"),
)


def fetch_png(commons_file: str, dest: Path, width: int = 320) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.is_file() and dest.stat().st_size > 1000:
        return
    url = f"https://commons.wikimedia.org/wiki/Special:FilePath/{urllib.parse.quote(commons_file)}?width={width}"
    print(f"fetch {commons_file}")
    req = urllib.request.Request(url, headers={"User-Agent": "astrolabe-embed-chakra/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        dest.write_bytes(resp.read())


def to_alpha_mask(im: Image.Image, size: int) -> Image.Image:
    im = im.convert("RGBA")
    im = im.resize((size, size), Image.Resampling.LANCZOS)
    px = im.load()
    out = Image.new("L", (size, size), 0)
    opx = out.load()
    for y in range(size):
        for x in range(size):
            r, g, b, a = px[x, y]
            lum = (r * 299 + g * 587 + b * 114) // 1000
            # Yantras: light lines on white — invert so ink is opaque.
            if lum > 245 and a > 8:
                alpha = 0
            else:
                edge = max(0, 255 - lum)
                alpha = min(255, edge * a // 255 + 24)
            opx[x, y] = alpha
    return out.point(lambda p: min(255, int(p * 1.05 + 6)))


def write_glyph_files(out_dir: Path, size: int, alphas: list[list[int]], names: tuple[str, ...]) -> None:
    path = out_dir / "chakra_glyphs.h"
    lines = [
        "// Auto-generated by scripts/embed_chakra_glyphs.py — do not edit.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define CHAKRA_GLYPH_SIZE {size}",
        f"#define CHAKRA_GLYPH_COUNT {len(alphas)}",
        "",
        "extern const uint8_t kChakraGlyphAlpha[CHAKRA_GLYPH_COUNT][CHAKRA_GLYPH_SIZE * CHAKRA_GLYPH_SIZE];",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")

    cpp_path = out_dir / "chakra_glyphs.cpp"
    cpp_lines = [
        "// Auto-generated by scripts/embed_chakra_glyphs.py — do not edit.",
        '#include "chakra_glyphs.h"',
        "",
        "#include <pgmspace.h>",
        "",
        f"const uint8_t kChakraGlyphAlpha[CHAKRA_GLYPH_COUNT][CHAKRA_GLYPH_SIZE * CHAKRA_GLYPH_SIZE] PROGMEM = {{",
    ]
    for slug, alpha in zip(names, alphas):
        cpp_lines.append(f"  // {slug}")
        cpp_lines.append("  {")
        for y in range(size):
            row = alpha[y * size : (y + 1) * size]
            hexes = ", ".join(f"0x{b:02x}" for b in row)
            cpp_lines.append(f"    {hexes},")
        cpp_lines.append("  },")
    cpp_lines.append("};")
    cpp_lines.append("")
    cpp_path.write_text("\n".join(cpp_lines), encoding="utf-8")
    print(f"Wrote {out_dir}/chakra_glyphs.* ({size}x{size}, {len(alphas)} chakras)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=96, help="Glyph square size in pixels")
    ap.add_argument("--skip-fetch", action="store_true")
    args = ap.parse_args()

    names = tuple(slug for slug, _ in CHAKRAS)
    alphas: list[list[int]] = []
    for slug, commons_file in CHAKRAS:
        png_path = ASSETS / f"{slug}.png"
        if not args.skip_fetch:
            fetch_png(commons_file, png_path)
        if not png_path.is_file():
            print(f"missing {png_path}", file=sys.stderr)
            return 1
        im = Image.open(png_path)
        mask = to_alpha_mask(im, args.size)
        alphas.append(list(mask.get_flattened_data()))

    write_glyph_files(OUT_DIR, args.size, alphas, names)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
