#!/usr/bin/env python3
"""Build an embedded RGB565 Earth texture for the Globe face."""

from __future__ import annotations

import argparse
import math
import random
import textwrap
import urllib.request
from pathlib import Path

from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_URL = (
    "https://eoimages.gsfc.nasa.gov/images/imagerecords/57000/57730/land_ocean_ice_2048.jpg"
)
DEFAULT_OUT = ROOT / "sketches" / "Astrolabe" / "faces" / "globe" / "globe_texture.h"
DEFAULT_PREVIEW = ROOT / "sketches" / "Astrolabe" / "faces" / "globe" / "globe_texture_preview.png"


def download(url: str, dest: Path) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists() and dest.stat().st_size > 0:
        return dest
    with urllib.request.urlopen(url, timeout=45) as response:
        dest.write_bytes(response.read())
    return dest


def make_cloud_mask(w: int, h: int) -> Image.Image:
    rng = random.Random(0xA5701ABE)
    mask = Image.new("L", (w, h), 0)
    for scale, alpha, blur in ((6, 32, 2), (12, 36, 4), (24, 42, 7), (48, 46, 11)):
        nw = max(2, w // scale)
        nh = max(2, h // scale)
        noise = Image.new("L", (nw, nh))
        noise.putdata([rng.randrange(256) for _ in range(nw * nh)])
        noise = noise.resize((w, h), Image.Resampling.BICUBIC).filter(ImageFilter.GaussianBlur(blur))
        mask = Image.blend(mask, noise, alpha / 255.0)

    mask = mask.point(lambda p: 0 if p < 76 else min(118, int((p - 76) * 1.55)))
    px = mask.load()
    for y in range(h):
        lat = abs((y + 0.5) / h - 0.5) * 2.0
        band = 0.62 + 0.38 * math.cos((lat - 0.28) * math.pi)
        for x in range(w):
            px[x, y] = int(px[x, y] * max(0.25, min(1.0, band)))
    return mask.filter(ImageFilter.GaussianBlur(1.4))


def enhance_texture(src: Image.Image, width: int, add_clouds: bool) -> Image.Image:
    height = width // 2
    im = src.convert("RGB").resize((width, height), Image.Resampling.LANCZOS)
    px = im.load()
    for y in range(height):
        lat = (0.5 - (y + 0.5) / height) * math.pi
        polar = abs(math.sin(lat))
        for x in range(width):
            r, g, b = px[x, y]
            ocean = b > g + 16 and b > r + 24
            if ocean:
                r = int(r * 0.72)
                g = int(g * 0.82)
                b = min(255, int(b * 1.12 + 8))
            else:
                r = min(255, int(r * 1.05 + 3))
                g = min(255, int(g * 1.05 + 2))
                b = int(b * 0.94)
            if polar > 0.82:
                ice = int((polar - 0.82) / 0.18 * 34)
                r = min(255, r + ice)
                g = min(255, g + ice)
                b = min(255, b + ice)
            px[x, y] = (r, g, b)

    if add_clouds:
        cloud = make_cloud_mask(width, height)
        cloud_rgb = Image.new("RGB", (width, height), (248, 250, 252))
        im = Image.composite(cloud_rgb, im, cloud)
    return im


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def write_header(im: Image.Image, out: Path, source: str, clouds: bool) -> None:
    values = [rgb565(r, g, b) for r, g, b in im.getdata()]
    rows = []
    for i in range(0, len(values), 12):
        rows.append("  " + ", ".join(f"0x{v:04x}" for v in values[i : i + 12]) + ",")
    body = "\n".join(rows)
    text = f"""\
// Auto-generated by scripts/embed_globe_texture.py; do not edit by hand.
// Source: NASA Blue Marble / MODIS land_ocean_ice_2048.jpg.
// Cloud layer: deterministic generated overlay baked into the texture.
#pragma once

#include <Arduino.h>

static constexpr int kGlobeTextureW = {im.width};
static constexpr int kGlobeTextureH = {im.height};
static constexpr int kGlobeTexturePixels = kGlobeTextureW * kGlobeTextureH;
static constexpr bool kGlobeTextureHasGeneratedClouds = {'true' if clouds else 'false'};
static constexpr const char *kGlobeTextureSource = "{source}";

static const uint16_t kGlobeTextureRgb565[kGlobeTexturePixels] PROGMEM = {{
{body}
}};
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-url", default=DEFAULT_SOURCE_URL)
    parser.add_argument("--download", type=Path, default=ROOT / ".cache" / "land_ocean_ice_2048.jpg")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--preview", type=Path, default=DEFAULT_PREVIEW)
    parser.add_argument("--width", type=int, default=720)
    parser.add_argument("--no-clouds", action="store_true")
    args = parser.parse_args()

    if args.width <= 0 or args.width % 2:
        raise ValueError("--width must be a positive even number")

    src_path = download(args.source_url, args.download.expanduser().resolve())
    with Image.open(src_path) as src:
      texture = enhance_texture(src, args.width, not args.no_clouds)
    write_header(texture, args.out.expanduser().resolve(), args.source_url, not args.no_clouds)
    if args.preview:
        args.preview.expanduser().resolve().parent.mkdir(parents=True, exist_ok=True)
        texture.save(args.preview.expanduser().resolve())
    print(textwrap.dedent(
        f"""\
        wrote {args.out}
        preview {args.preview}
        size {texture.width}x{texture.height}
        clouds {'yes' if not args.no_clouds else 'no'}
        """
    ).strip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
