#!/usr/bin/env python3
"""Build sketches/Astrolabe/faces/astrology/planet_glyphs.* — alpha masks for chart bodies."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("pip install pillow", file=sys.stderr)
    raise

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "sketches" / "Astrolabe" / "faces" / "astrology"

# Order matches PmBodyId in pm_transit.h (sun … saturn).
PLANETS = "☉☽☿♀♂♃♄"
NAMES = ("sun", "moon", "mercury", "venus", "mars", "jupiter", "saturn")

FONT_CANDIDATES = [
    "/System/Library/Fonts/Apple Symbols.ttf",
    "/System/Library/Fonts/Supplemental/Apple Symbols.ttf",
    "/System/Library/Fonts/Supplemental/Symbola.ttf",
    "/Library/Fonts/Symbola.ttf",
    "/usr/share/fonts/truetype/ancient-scripts/Symbola.ttf",
    "/usr/share/fonts/truetype/noto/NotoSansSymbols2-Regular.ttf",
    "/usr/share/fonts/opentype/noto/NotoSansSymbols2-Regular.ttf",
    "/Library/Fonts/Arial Unicode.ttf",
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
    "C:/Windows/Fonts/seguisym.ttf",
]


def find_font() -> Path:
    for p in FONT_CANDIDATES:
        if Path(p).is_file():
            return Path(p)
    raise FileNotFoundError(
        "No symbol font found (Symbola / Noto Sans Symbols 2). "
        "Install Symbola or pass --font PATH."
    )


def render_glyph(ch: str, size: int, font: ImageFont.FreeTypeFont) -> Image.Image:
    pad = 6
    canvas = size + pad * 2
    im = Image.new("L", (canvas, canvas), 0)
    draw = ImageDraw.Draw(im)
    bbox = draw.textbbox((0, 0), ch, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    ox = (canvas - tw) // 2 - bbox[0]
    oy = (canvas - th) // 2 - bbox[1]
    draw.text((ox, oy), ch, fill=255, font=font)
    left = (canvas - size) // 2
    top = (canvas - size) // 2
    out = im.crop((left, top, left + size, top + size))
    out = out.point(lambda p: min(255, int(p * 1.08 + 4)))
    return out


def write_glyph_files(out_dir: Path, size: int, alphas: list[list[int]]) -> None:
    path = out_dir / "planet_glyphs.h"
    lines = [
        "// Auto-generated by scripts/embed_planet_glyphs.py — do not edit.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define PLANET_GLYPH_SIZE {size}",
        f"#define PLANET_GLYPH_COUNT {len(alphas)}",
        "",
        "extern const uint8_t kPlanetGlyphAlpha[PLANET_GLYPH_COUNT][PLANET_GLYPH_SIZE * PLANET_GLYPH_SIZE];",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")

    cpp_path = path.with_suffix(".cpp")
    cpp_lines = [
        "// Auto-generated by scripts/embed_planet_glyphs.py — do not edit.",
        '#include "planet_glyphs.h"',
        "",
        "#include <pgmspace.h>",
        "",
        f"const uint8_t kPlanetGlyphAlpha[PLANET_GLYPH_COUNT][PLANET_GLYPH_SIZE * PLANET_GLYPH_SIZE] PROGMEM = {{",
    ]
    for name, alpha in zip(NAMES, alphas):
        cpp_lines.append(f"  // {name}")
        cpp_lines.append("  {")
        for y in range(size):
            row = alpha[y * size : (y + 1) * size]
            hexes = ", ".join(f"0x{b:02x}" for b in row)
            cpp_lines.append(f"    {hexes},")
        cpp_lines.append("  },")
    cpp_lines.append("};")
    cpp_lines.append("")
    cpp_path.write_text("\n".join(cpp_lines), encoding="utf-8")
    print(f"Wrote {out_dir}/planet_glyphs.* ({size}x{size}, {len(alphas)} bodies)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=22, help="Glyph square size in pixels")
    ap.add_argument("--font", type=Path, default=None, help="TTF with astrological symbols")
    args = ap.parse_args()

    font_path = args.font if args.font else find_font()
    print(f"Font: {font_path}")
    font = ImageFont.truetype(str(font_path), int(args.size * 0.92))

    alphas: list[list[int]] = []
    for ch in PLANETS:
        im = render_glyph(ch, args.size, font)
        alphas.append(list(im.get_flattened_data()))

    write_glyph_files(OUT_DIR, args.size, alphas)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
