#!/usr/bin/env python3
"""Build moon_texture.h — 8-bit greyscale moon (PROGMEM), circular mask in pm_moon_draw."""
from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

try:
    from PIL import Image, ImageEnhance
except ImportError:
    print("pip install pillow", file=sys.stderr)
    raise

DEFAULT_URL = "https://upload.wikimedia.org/wikipedia/commons/e/e1/FullMoon2010.jpg"
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "sketches" / "Astrolabe" / "faces" / "moon" / "moon_texture.h"


def load_source(path: Path | None, url: str) -> Image.Image:
    if path and path.is_file():
        im = Image.open(path).convert("RGB")
    else:
        print(f"Downloading {url} …")
        req = urllib.request.Request(url, headers={"User-Agent": "CastaliaInstitute-astrolabe/1.0"})
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = resp.read()
        from io import BytesIO

        im = Image.open(BytesIO(data)).convert("RGB")
    return im


def build_texture(im: Image.Image, size: int) -> list[int]:
    """Center-crop, resize, circular mask; return 8-bit grey (0 outside disk)."""
    w, h = im.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    im = im.crop((left, top, left + side, top + side))
    im = im.resize((size, size), Image.Resampling.LANCZOS)
    im = ImageEnhance.Contrast(im).enhance(1.06)
    im = ImageEnhance.Brightness(im).enhance(0.97)
    gray_im = im.convert("L")

    gray: list[int] = []
    cx = cy = size / 2.0
    r = size / 2.0 - 0.5
    r2 = r * r
    for y in range(size):
        for x in range(size):
            dx = x - cx
            dy = y - cy
            if dx * dx + dy * dy > r2:
                gray.append(0)
                continue
            gray.append(int(gray_im.getpixel((x, y))))
    return gray


def write_header(path: Path, size: int, gray: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    n = size * size
    lines = [
        "// Auto-generated by scripts/embed_moon_texture.py — do not edit.",
        "// Source: Wikimedia FullMoon2010 (public domain). 8-bit grey; disk mask in pm_moon_draw.",
        "#pragma once",
        "#include <stdint.h>",
        f"#define MOON_TEX_SIZE {size}",
        f"#define MOON_TEX_PIXELS {n}",
        "",
        f"static const uint8_t kMoonTextureGray[MOON_TEX_PIXELS] PROGMEM = {{",
    ]
    buf = "  "
    for i, v in enumerate(gray):
        buf += f"{v},"
        if (i + 1) % 24 == 0:
            lines.append(buf)
            buf = "  "
    if buf.strip():
        lines.append(buf.rstrip(","))
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {path} ({n} pixels, {n // 1024} KiB grey PROGMEM)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=320, help="texture side in pixels (default 320)")
    ap.add_argument("--input", type=Path, default=None)
    ap.add_argument("--url", default=DEFAULT_URL)
    ap.add_argument("-o", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    im = load_source(args.input, args.url)
    gray = build_texture(im, args.size)
    write_header(args.o, args.size, gray)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
