#!/usr/bin/env python3
"""Generate Astrolabe Castalian Rhythms KB flash data from source JSON."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "sketches" / "Astrolabe" / "rhythms_kb" / "v0" / "manifest.json"
DEFAULT_OUT = ROOT / "sketches" / "Astrolabe" / "pm_rhythms_kb_data.cpp"

KEY_RE = re.compile(r"^[a-z0-9][a-z0-9_.-]*$")
AUTO_BANNER = "// Auto-generated by scripts/embed_rhythms_kb.py - do not edit."


class KbError(ValueError):
    pass


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def as_text(value: Any, field: str, key: str) -> str:
    if isinstance(value, str):
        text = value
    elif isinstance(value, list) and all(isinstance(item, str) for item in value):
        text = " | ".join(value)
    else:
        raise KbError(f"{key}: {field} must be a string or list of strings")
    text = " ".join(text.split())
    if not text:
        raise KbError(f"{key}: {field} must not be empty")
    return text


def as_tags(value: Any, key: str) -> str:
    if not isinstance(value, list) or not value or not all(isinstance(item, str) for item in value):
        raise KbError(f"{key}: tags must be a non-empty list of strings")
    tags = []
    for tag in value:
        tag = tag.strip()
        if not KEY_RE.match(tag.replace(":", "_")):
            raise KbError(f"{key}: invalid tag {tag!r}")
        tags.append(tag)
    return ",".join(tags)


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def validate_entries(manifest: dict[str, Any], raw_entries: Any) -> list[dict[str, str]]:
    if not isinstance(raw_entries, list):
        raise KbError("entries JSON must be a list")

    required_fields = {
        "interpretation_key",
        "category",
        "title",
        "tags",
        "summary",
        "invitations",
        "cautions",
        "practices",
        "safety_level",
    }
    categories = set(manifest.get("categories", []))
    safety_levels = set(manifest.get("safety_levels", []))
    minimum_entries = int(manifest.get("minimum_entries", 0))
    seen: set[str] = set()
    entries: list[dict[str, str]] = []

    for idx, raw in enumerate(raw_entries):
        if not isinstance(raw, dict):
            raise KbError(f"entry {idx}: must be an object")
        missing = required_fields - raw.keys()
        if missing:
            raise KbError(f"entry {idx}: missing fields {sorted(missing)}")

        key = str(raw["interpretation_key"]).strip()
        if not KEY_RE.match(key):
            raise KbError(f"entry {idx}: invalid interpretation_key {key!r}")
        if key in seen:
            raise KbError(f"duplicate interpretation_key {key!r}")
        seen.add(key)

        category = str(raw["category"]).strip()
        if categories and category not in categories:
            raise KbError(f"{key}: unknown category {category!r}")
        safety_level = str(raw["safety_level"]).strip()
        if safety_levels and safety_level not in safety_levels:
            raise KbError(f"{key}: unknown safety_level {safety_level!r}")

        entries.append(
            {
                "interpretation_key": key,
                "category": category,
                "title": as_text(raw["title"], "title", key),
                "tags": as_tags(raw["tags"], key),
                "summary": as_text(raw["summary"], "summary", key),
                "invitations": as_text(raw["invitations"], "invitations", key),
                "cautions": as_text(raw["cautions"], "cautions", key),
                "practices": as_text(raw["practices"], "practices", key),
                "safety_level": safety_level,
            }
        )

    if len(entries) < minimum_entries:
        raise KbError(f"manifest requires at least {minimum_entries} entries; found {len(entries)}")

    for prefix in manifest.get("required_prefixes", []):
        if not any(entry["interpretation_key"].startswith(prefix) for entry in entries):
            raise KbError(f"required_prefixes missing {prefix!r}")

    for key in manifest.get("required_keys", []):
        if key not in seen:
            raise KbError(f"required_keys missing {key!r}")

    return sorted(entries, key=lambda entry: entry["interpretation_key"])


def write_cpp(out_path: Path, manifest_path: Path, entries_path: Path, entries: list[dict[str, str]]) -> None:
    lines = [
        AUTO_BANNER,
        f"// Source manifest: {manifest_path.relative_to(ROOT).as_posix()}",
        f"// Source entries: {entries_path.relative_to(ROOT).as_posix()}",
        '#include "pm_rhythms_kb.h"',
        "",
        "#include <pgmspace.h>",
        "",
        "const PmRhythmsKbEntry kPmRhythmsKbEntries[] PROGMEM = {",
    ]
    for entry in entries:
        lines.extend(
            [
                f"  // {entry['interpretation_key']}",
                "  {",
                f"    {c_string(entry['interpretation_key'])},",
                f"    {c_string(entry['category'])},",
                f"    {c_string(entry['title'])},",
                f"    {c_string(entry['tags'])},",
                f"    {c_string(entry['summary'])},",
                f"    {c_string(entry['invitations'])},",
                f"    {c_string(entry['cautions'])},",
                f"    {c_string(entry['practices'])},",
                f"    {c_string(entry['safety_level'])},",
                "  },",
            ]
        )
    lines.extend(
        [
            "};",
            "",
            "const size_t kPmRhythmsKbEntryCount = sizeof(kPmRhythmsKbEntries) / sizeof(kPmRhythmsKbEntries[0]);",
            "",
        ]
    )
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="Rhythms KB manifest JSON")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Generated C++ data output")
    args = parser.parse_args()

    manifest_path = args.manifest.resolve()
    manifest = load_json(manifest_path)
    if not isinstance(manifest, dict):
        raise KbError("manifest must be a JSON object")
    entries_path = (manifest_path.parent / str(manifest.get("entries", "entries.json"))).resolve()
    entries = validate_entries(manifest, load_json(entries_path))

    out_path = args.out.resolve()
    write_cpp(out_path, manifest_path, entries_path, entries)
    print(f"Wrote {out_path.relative_to(ROOT)} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
