#!/usr/bin/env python3
"""Generate 466x466 greyscale moon texture for PocketMynah (LCD size)."""

from __future__ import annotations

import math
import random
import struct
import zlib
from pathlib import Path

SIZE = 466
ROOT = Path(__file__).resolve().parents[1]
OUT_PNG = ROOT / "sketches" / "PocketMynah" / "assets" / "moon_466_gray.png"
OUT_H = ROOT / "sketches" / "PocketMynah" / "pm_moon_tex.h"
OUT_C = ROOT / "sketches" / "PocketMynah" / "pm_moon_tex.c"


def make_texture() -> list[int]:
    rng = random.Random(0x6D6F6F6E)
    craters: list[tuple[float, float, float, float]] = []
    n_craters = 220
    for _ in range(n_craters):
        craters.append(
            (
                rng.uniform(0.06, 0.94),
                rng.uniform(0.06, 0.94),
                rng.uniform(0.008, 0.055),
                rng.uniform(0.35, 1.0),
            )
        )

    px: list[int] = []
    for y in range(SIZE):
        for x in range(SIZE):
            nx = (x + 0.5) / SIZE - 0.5
            ny = (y + 0.5) / SIZE - 0.5
            d = math.hypot(nx, ny)
            if d > 0.5:
                px.append(0)
                continue
            z = math.sqrt(max(0.0, 0.25 - d * d))
            shade = 0.52 + 0.48 * (z / 0.5)
            g = int(172 * shade + 22)
            for mx, my, mr, depth in (
                (0.38, 0.42, 0.18, 0.24),
                (0.58, 0.55, 0.14, 0.20),
                (0.22, 0.62, 0.12, 0.17),
                (0.68, 0.28, 0.10, 0.14),
                (0.48, 0.72, 0.09, 0.12),
            ):
                dd = math.hypot(nx - (mx - 0.5), ny - (my - 0.5))
                if dd < mr:
                    f = 1.0 - depth * (1.0 - dd / mr)
                    g = int(g * f)
            for cx, cy, rad, depth in craters:
                dd = math.hypot(nx - (cx - 0.5), ny - (cy - 0.5))
                if dd < rad:
                    rim = abs(dd - rad * 0.72) < rad * 0.09
                    if rim:
                        lift = 1.0 + 0.14 * depth
                        g = min(255, int(g * lift))
                    else:
                        f = 1.0 - depth * (1.0 - dd / rad) * 0.58
                        g = int(g * f)
            n = rng.uniform(-8, 8)
            g = max(0, min(255, int(g + n)))
            px.append(g)
    return px


def write_png_gray(path: Path, width: int, height: int, gray: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = bytearray()
    for y in range(height):
        raw.append(0)
        raw.extend(gray[y * width : (y + 1) * width])
    compressed = zlib.compress(bytes(raw), 9)

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 0, 0, 0, 0)
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", compressed) + chunk(b"IEND", b"")
    path.write_bytes(png)


def emit_c(gray: list[int]) -> None:
    lines = [
        "// Auto-generated by scripts/gen_moon_tex.py — do not edit by hand.",
        '#include "pm_moon_tex.h"',
        "",
        "#if defined(__AVR__)",
        '#include <avr/pgmspace.h>',
        "#elif defined(ESP8266) || defined(ESP32)",
        '#include <pgmspace.h>',
        "#else",
        '#define PROGMEM',
        "#endif",
        "",
        f"const uint8_t kPmMoonTexGray[kPmMoonTexPixels] PROGMEM = {{",
    ]
    for i in range(0, len(gray), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in gray[i : i + 16])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append("")
    OUT_C.write_text("\n".join(lines), encoding="utf-8")


def emit_h() -> None:
    OUT_H.write_text(
        "\n".join(
            [
                "// Auto-generated by scripts/gen_moon_tex.py — do not edit by hand.",
                "#pragma once",
                "",
                "#include <stdint.h>",
                "",
                "#ifdef __cplusplus",
                "extern \"C\" {",
                "#endif",
                "",
                f"#define kPmMoonTexSize {SIZE}",
                f"#define kPmMoonTexPixels ({SIZE} * {SIZE})",
                f"extern const uint8_t kPmMoonTexGray[kPmMoonTexPixels];",
                "",
                "#ifdef __cplusplus",
                "}",
                "#endif",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    gray = make_texture()
    write_png_gray(OUT_PNG, SIZE, SIZE, gray)
    emit_h()
    emit_c(gray)
    print(f"Wrote {OUT_PNG} ({OUT_PNG.stat().st_size} bytes)")
    print(f"Wrote {OUT_H}")
    print(f"Wrote {OUT_C} ({len(gray)} bytes PROGMEM)")


if __name__ == "__main__":
    main()
