#!/usr/bin/env python3
"""Generate compact horizontal spans for Theritor's Emojinq expressions."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


GLYPHS = (
    ("calm", "🙂"),
    ("thinking", "🤔"),
    ("examining", "🧐"),
    ("concerned", "😟"),
    ("warm", "😊"),
    ("relieved", "😌"),
)


def spans_for(font: ImageFont.FreeTypeFont, glyph: str, size: int) -> list[tuple[int, int, int]]:
    source_size = size * 2
    image = Image.new("L", (source_size, source_size), 0)
    draw = ImageDraw.Draw(image)
    left, top, right, bottom = draw.textbbox((0, 0), glyph, font=font)
    x = (source_size - (right - left)) // 2 - left
    y = (source_size - (bottom - top)) // 2 - top
    draw.text((x, y), glyph, fill=255, font=font)

    bounds = image.getbbox()
    if bounds is None:
        return []
    cropped = image.crop(bounds)
    available = size - 8
    scale = min(available / cropped.width, available / cropped.height)
    resized = cropped.resize(
        (max(1, round(cropped.width * scale)), max(1, round(cropped.height * scale))),
        Image.Resampling.LANCZOS,
    )
    image = Image.new("L", (size, size), 0)
    image.paste(resized, ((size - resized.width) // 2, (size - resized.height) // 2))

    pixels = image.load()
    spans: list[tuple[int, int, int]] = []
    for row in range(size):
        start = -1
        for col in range(size + 1):
            filled = col < size and pixels[col, row] >= 64
            if filled and start < 0:
                start = col
            elif not filled and start >= 0:
                spans.append((row, start, col - 1))
                start = -1
    return spans


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--size", type=int, default=390)
    args = parser.parse_args()

    font = ImageFont.truetype(str(args.font), args.size * 2)
    lines = [
        "/* Generated by scripts/gen_theritor_emojinq.py; do not edit. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define THERITOR_EMOJINQ_SIZE {args.size}",
        "",
        "typedef struct {",
        "    uint16_t y;",
        "    uint16_t x0;",
        "    uint16_t x1;",
        "} theritor_emojinq_span_t;",
        "",
    ]
    descriptors = []
    for name, glyph in GLYPHS:
        spans = spans_for(font, glyph, args.size)
        array_name = f"k_theritor_emojinq_{name}"
        lines.append(f"/* {glyph} U+{ord(glyph):04X} */")
        lines.append(f"static const theritor_emojinq_span_t {array_name}[] = {{")
        for y, x0, x1 in spans:
            lines.append(f"    {{{y}, {x0}, {x1}}},")
        lines.append("};")
        lines.append("")
        descriptors.append((array_name, len(spans)))

    lines.extend([
        "typedef struct {",
        "    const theritor_emojinq_span_t *spans;",
        "    uint16_t count;",
        "} theritor_emojinq_glyph_t;",
        "",
        "static const theritor_emojinq_glyph_t k_theritor_emojinq_glyphs[] = {",
    ])
    for array_name, count in descriptors:
        lines.append(f"    {{{array_name}, {count}}},")
    lines.extend(["};", ""])
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
