#!/usr/bin/env python3
"""Generate pm_moon_tex.h — RGB565 full-moon surface for PocketMynah."""

from __future__ import annotations

import math
import random
from pathlib import Path

SIZE = 128
OUT = Path(__file__).resolve().parents[1] / "sketches" / "PocketMynah" / "pm_moon_tex.h"


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def make_texture() -> list[int]:
    rng = random.Random(0x6D6F6F6E)
    craters: list[tuple[float, float, float, float]] = []
    for _ in range(42):
        craters.append(
            (
                rng.uniform(0.08, 0.92),
                rng.uniform(0.08, 0.92),
                rng.uniform(0.03, 0.14),
                rng.uniform(0.35, 1.0),
            )
        )

    px: list[int] = []
    for y in range(SIZE):
        for x in range(SIZE):
            nx = (x + 0.5) / SIZE - 0.5
            ny = (y + 0.5) / SIZE - 0.5
            d = math.hypot(nx, ny)
            if d > 0.5:
                px.append(0)
                continue
            # Spherical shading (limb darkening)
            z = math.sqrt(max(0.0, 0.25 - d * d))
            shade = 0.55 + 0.45 * (z / 0.5)
            r = g = b = int(168 * shade + 24)
            # Mare (darker basalt patches)
            for mx, my, mr, depth in (
                (0.38, 0.42, 0.18, 0.22),
                (0.58, 0.55, 0.14, 0.18),
                (0.22, 0.62, 0.12, 0.15),
                (0.68, 0.28, 0.10, 0.12),
            ):
                dd = math.hypot(nx - (mx - 0.5), ny - (my - 0.5))
                if dd < mr:
                    f = 1.0 - depth * (1.0 - dd / mr)
                    r = int(r * f)
                    g = int(g * f)
                    b = int(b * f)
            # Craters
            for cx, cy, rad, depth in craters:
                dd = math.hypot(nx - (cx - 0.5), ny - (cy - 0.5))
                if dd < rad:
                    rim = abs(dd - rad * 0.72) < rad * 0.08
                    if rim:
                        lift = 1.0 + 0.12 * depth
                        r = min(255, int(r * lift))
                        g = min(255, int(g * lift))
                        b = min(255, int(b * lift))
                    else:
                        f = 1.0 - depth * (1.0 - dd / rad) * 0.55
                        r = int(r * f)
                        g = int(g * f)
                        b = int(b * f)
            # Fine noise
            n = rng.uniform(-10, 10)
            r = max(0, min(255, int(r + n)))
            g = max(0, min(255, int(g + n)))
            b = max(0, min(255, int(b + n - 4)))
            px.append(rgb565(r, g, b))
    return px


def emit(data: list[int]) -> None:
    lines = [
        "// Auto-generated by scripts/gen_moon_tex.py — do not edit by hand.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        "",
        f"static constexpr int kPmMoonTexSize = {SIZE};",
        f"static const uint16_t kPmMoonTexRgb565[{SIZE * SIZE}] PROGMEM = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{v:04X}" for v in data[i : i + 12])
        lines.append(f"  {chunk},")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(data) * 2} bytes)")


if __name__ == "__main__":
    emit(make_texture())
