#!/usr/bin/env bash
# Write include/secrets.local.h from environment (GitHub Actions secrets or local export).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/include/secrets.local.h"

for var in MYNAH_WIFI_SSID MYNAH_WIFI_PASSWORD MYNAH_SUPABASE_URL MYNAH_SUPABASE_ANON_KEY; do
  if [[ -z "${!var:-}" ]]; then
    echo "error: unset ${var} (set GitHub Actions secrets or export locally)" >&2
    exit 1
  fi
done

cat >"$OUT" <<EOF
#pragma once
// Generated by scripts/write_secrets_ci.sh — do not commit.
#define MYNAH_WIFI_SSID "${MYNAH_WIFI_SSID}"
#define MYNAH_WIFI_PASSWORD "${MYNAH_WIFI_PASSWORD}"
#define MYNAH_SUPABASE_URL "${MYNAH_SUPABASE_URL}"
#define MYNAH_SUPABASE_ANON_KEY "${MYNAH_SUPABASE_ANON_KEY}"
#ifndef MYNAH_CASTALIA_WEB_ORIGIN
#define MYNAH_CASTALIA_WEB_ORIGIN "${MYNAH_CASTALIA_WEB_ORIGIN:-https://inquiry.institute}"
#endif
EOF
echo "→ wrote ${OUT}"
